services:
  livekit:
    image: livekit/livekit-server
    command: --dev --bind 0.0.0.0 --node-ip ${LIVEKIT_NODE_IP:-0.0.0.0}
    network_mode: host
    environment:
      - LIVEKIT_NODE_IP=${LIVEKIT_NODE_IP:-}
    restart: unless-stopped
