# automatically generated by the FlatBuffers compiler, do not modify

# namespace: teleop

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class CartesianState:
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CartesianState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCartesianState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # CartesianState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CartesianState
    def HandSide(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CartesianState
    def PositionMeters(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Float32Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4),
            )
        return 0

    # CartesianState
    def PositionMetersAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # CartesianState
    def PositionMetersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CartesianState
    def PositionMetersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # CartesianState
    def OrientationQuat(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Float32Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4),
            )
        return 0

    # CartesianState
    def OrientationQuatAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # CartesianState
    def OrientationQuatLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CartesianState
    def OrientationQuatIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # CartesianState
    def HomoMatrix(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Float32Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4),
            )
        return 0

    # CartesianState
    def HomoMatrixAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # CartesianState
    def HomoMatrixLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CartesianState
    def HomoMatrixIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # CartesianState
    def Command(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CartesianState
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0


def CartesianStateStart(builder):
    builder.StartObject(6)


def Start(builder):
    return CartesianStateStart(builder)


def CartesianStateAddHandSide(builder, handSide):
    builder.PrependUint8Slot(0, handSide, 0)


def AddHandSide(builder, handSide):
    return CartesianStateAddHandSide(builder, handSide)


def CartesianStateAddPositionMeters(builder, positionMeters):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(positionMeters), 0)


def AddPositionMeters(builder, positionMeters):
    return CartesianStateAddPositionMeters(builder, positionMeters)


def CartesianStateStartPositionMetersVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartPositionMetersVector(builder, numElems):
    return CartesianStateStartPositionMetersVector(builder, numElems)


def CartesianStateAddOrientationQuat(builder, orientationQuat):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(orientationQuat), 0)


def AddOrientationQuat(builder, orientationQuat):
    return CartesianStateAddOrientationQuat(builder, orientationQuat)


def CartesianStateStartOrientationQuatVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartOrientationQuatVector(builder, numElems):
    return CartesianStateStartOrientationQuatVector(builder, numElems)


def CartesianStateAddHomoMatrix(builder, homoMatrix):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(homoMatrix), 0)


def AddHomoMatrix(builder, homoMatrix):
    return CartesianStateAddHomoMatrix(builder, homoMatrix)


def CartesianStateStartHomoMatrixVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartHomoMatrixVector(builder, numElems):
    return CartesianStateStartHomoMatrixVector(builder, numElems)


def CartesianStateAddCommand(builder, command):
    builder.PrependUint8Slot(4, command, 0)


def AddCommand(builder, command):
    return CartesianStateAddCommand(builder, command)


def CartesianStateAddTimestamp(builder, timestamp):
    builder.PrependFloat64Slot(5, timestamp, 0.0)


def AddTimestamp(builder, timestamp):
    return CartesianStateAddTimestamp(builder, timestamp)


def CartesianStateEnd(builder):
    return builder.EndObject()


def End(builder):
    return CartesianStateEnd(builder)


try:
    pass
except:
    pass


class CartesianStateT:
    # CartesianStateT
    def __init__(self):
        self.handSide = 0  # type: int
        self.positionMeters = None  # type: List[float]
        self.orientationQuat = None  # type: List[float]
        self.homoMatrix = None  # type: List[float]
        self.command = 0  # type: int
        self.timestamp = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cartesianState = CartesianState()
        cartesianState.Init(buf, pos)
        return cls.InitFromObj(cartesianState)

    @classmethod
    def InitFromObj(cls, cartesianState):
        x = CartesianStateT()
        x._UnPack(cartesianState)
        return x

    # CartesianStateT
    def _UnPack(self, cartesianState):
        if cartesianState is None:
            return
        self.handSide = cartesianState.HandSide()
        if not cartesianState.PositionMetersIsNone():
            if np is None:
                self.positionMeters = []
                for i in range(cartesianState.PositionMetersLength()):
                    self.positionMeters.append(cartesianState.PositionMeters(i))
            else:
                self.positionMeters = cartesianState.PositionMetersAsNumpy()
        if not cartesianState.OrientationQuatIsNone():
            if np is None:
                self.orientationQuat = []
                for i in range(cartesianState.OrientationQuatLength()):
                    self.orientationQuat.append(cartesianState.OrientationQuat(i))
            else:
                self.orientationQuat = cartesianState.OrientationQuatAsNumpy()
        if not cartesianState.HomoMatrixIsNone():
            if np is None:
                self.homoMatrix = []
                for i in range(cartesianState.HomoMatrixLength()):
                    self.homoMatrix.append(cartesianState.HomoMatrix(i))
            else:
                self.homoMatrix = cartesianState.HomoMatrixAsNumpy()
        self.command = cartesianState.Command()
        self.timestamp = cartesianState.Timestamp()

    # CartesianStateT
    def Pack(self, builder):
        if self.positionMeters is not None:
            if np is not None and type(self.positionMeters) is np.ndarray:
                positionMeters = builder.CreateNumpyVector(self.positionMeters)
            else:
                CartesianStateStartPositionMetersVector(builder, len(self.positionMeters))
                for i in reversed(range(len(self.positionMeters))):
                    builder.PrependFloat32(self.positionMeters[i])
                positionMeters = builder.EndVector()
        if self.orientationQuat is not None:
            if np is not None and type(self.orientationQuat) is np.ndarray:
                orientationQuat = builder.CreateNumpyVector(self.orientationQuat)
            else:
                CartesianStateStartOrientationQuatVector(builder, len(self.orientationQuat))
                for i in reversed(range(len(self.orientationQuat))):
                    builder.PrependFloat32(self.orientationQuat[i])
                orientationQuat = builder.EndVector()
        if self.homoMatrix is not None:
            if np is not None and type(self.homoMatrix) is np.ndarray:
                homoMatrix = builder.CreateNumpyVector(self.homoMatrix)
            else:
                CartesianStateStartHomoMatrixVector(builder, len(self.homoMatrix))
                for i in reversed(range(len(self.homoMatrix))):
                    builder.PrependFloat32(self.homoMatrix[i])
                homoMatrix = builder.EndVector()
        CartesianStateStart(builder)
        CartesianStateAddHandSide(builder, self.handSide)
        if self.positionMeters is not None:
            CartesianStateAddPositionMeters(builder, positionMeters)
        if self.orientationQuat is not None:
            CartesianStateAddOrientationQuat(builder, orientationQuat)
        if self.homoMatrix is not None:
            CartesianStateAddHomoMatrix(builder, homoMatrix)
        CartesianStateAddCommand(builder, self.command)
        CartesianStateAddTimestamp(builder, self.timestamp)
        cartesianState = CartesianStateEnd(builder)
        return cartesianState
