# automatically generated by the FlatBuffers compiler, do not modify

# namespace: teleop

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CommandMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CommandMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCommandMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CommandMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CommandMessage
    def Command(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def CommandMessageStart(builder): builder.StartObject(1)
def Start(builder):
    return CommandMessageStart(builder)
def CommandMessageAddCommand(builder, command): builder.PrependUint8Slot(0, command, 0)
def AddCommand(builder, command):
    return CommandMessageAddCommand(builder, command)
def CommandMessageEnd(builder): return builder.EndObject()
def End(builder):
    return CommandMessageEnd(builder)

class CommandMessageT(object):

    # CommandMessageT
    def __init__(self):
        self.command = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        commandMessage = CommandMessage()
        commandMessage.Init(buf, pos)
        return cls.InitFromObj(commandMessage)

    @classmethod
    def InitFromObj(cls, commandMessage):
        x = CommandMessageT()
        x._UnPack(commandMessage)
        return x

    # CommandMessageT
    def _UnPack(self, commandMessage):
        if commandMessage is None:
            return
        self.command = commandMessage.Command()

    # CommandMessageT
    def Pack(self, builder):
        CommandMessageStart(builder)
        CommandMessageAddCommand(builder, self.command)
        commandMessage = CommandMessageEnd(builder)
        return commandMessage
