# automatically generated by the FlatBuffers compiler, do not modify

# namespace: teleop

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class InputFrame:
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InputFrame()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInputFrame(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # InputFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InputFrame
    def Keypoints(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Float32Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4),
            )
        return 0

    # InputFrame
    def KeypointsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # InputFrame
    def KeypointsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InputFrame
    def KeypointsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # InputFrame
    def HandSide(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # InputFrame
    def IsRelative(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # InputFrame
    def Command(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # InputFrame
    def CoordinateFrame(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Float32Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4),
            )
        return 0

    # InputFrame
    def CoordinateFrameAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # InputFrame
    def CoordinateFrameLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InputFrame
    def CoordinateFrameIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0


def InputFrameStart(builder):
    builder.StartObject(5)


def Start(builder):
    return InputFrameStart(builder)


def InputFrameAddKeypoints(builder, keypoints):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(keypoints), 0)


def AddKeypoints(builder, keypoints):
    return InputFrameAddKeypoints(builder, keypoints)


def InputFrameStartKeypointsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartKeypointsVector(builder, numElems):
    return InputFrameStartKeypointsVector(builder, numElems)


def InputFrameAddHandSide(builder, handSide):
    builder.PrependUint8Slot(1, handSide, 0)


def AddHandSide(builder, handSide):
    return InputFrameAddHandSide(builder, handSide)


def InputFrameAddIsRelative(builder, isRelative):
    builder.PrependUint8Slot(2, isRelative, 0)


def AddIsRelative(builder, isRelative):
    return InputFrameAddIsRelative(builder, isRelative)


def InputFrameAddCommand(builder, command):
    builder.PrependUint8Slot(3, command, 0)


def AddCommand(builder, command):
    return InputFrameAddCommand(builder, command)


def InputFrameAddCoordinateFrame(builder, coordinateFrame):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(coordinateFrame), 0)


def AddCoordinateFrame(builder, coordinateFrame):
    return InputFrameAddCoordinateFrame(builder, coordinateFrame)


def InputFrameStartCoordinateFrameVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartCoordinateFrameVector(builder, numElems):
    return InputFrameStartCoordinateFrameVector(builder, numElems)


def InputFrameEnd(builder):
    return builder.EndObject()


def End(builder):
    return InputFrameEnd(builder)


try:
    pass
except:
    pass


class InputFrameT:
    # InputFrameT
    def __init__(self):
        self.keypoints = None  # type: List[float]
        self.handSide = 0  # type: int
        self.isRelative = 0  # type: int
        self.command = 0  # type: int
        self.coordinateFrame = None  # type: List[float]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        inputFrame = InputFrame()
        inputFrame.Init(buf, pos)
        return cls.InitFromObj(inputFrame)

    @classmethod
    def InitFromObj(cls, inputFrame):
        x = InputFrameT()
        x._UnPack(inputFrame)
        return x

    # InputFrameT
    def _UnPack(self, inputFrame):
        if inputFrame is None:
            return
        if not inputFrame.KeypointsIsNone():
            if np is None:
                self.keypoints = []
                for i in range(inputFrame.KeypointsLength()):
                    self.keypoints.append(inputFrame.Keypoints(i))
            else:
                self.keypoints = inputFrame.KeypointsAsNumpy()
        self.handSide = inputFrame.HandSide()
        self.isRelative = inputFrame.IsRelative()
        self.command = inputFrame.Command()
        if not inputFrame.CoordinateFrameIsNone():
            if np is None:
                self.coordinateFrame = []
                for i in range(inputFrame.CoordinateFrameLength()):
                    self.coordinateFrame.append(inputFrame.CoordinateFrame(i))
            else:
                self.coordinateFrame = inputFrame.CoordinateFrameAsNumpy()

    # InputFrameT
    def Pack(self, builder):
        if self.keypoints is not None:
            if np is not None and type(self.keypoints) is np.ndarray:
                keypoints = builder.CreateNumpyVector(self.keypoints)
            else:
                InputFrameStartKeypointsVector(builder, len(self.keypoints))
                for i in reversed(range(len(self.keypoints))):
                    builder.PrependFloat32(self.keypoints[i])
                keypoints = builder.EndVector()
        if self.coordinateFrame is not None:
            if np is not None and type(self.coordinateFrame) is np.ndarray:
                coordinateFrame = builder.CreateNumpyVector(self.coordinateFrame)
            else:
                InputFrameStartCoordinateFrameVector(builder, len(self.coordinateFrame))
                for i in reversed(range(len(self.coordinateFrame))):
                    builder.PrependFloat32(self.coordinateFrame[i])
                coordinateFrame = builder.EndVector()
        InputFrameStart(builder)
        if self.keypoints is not None:
            InputFrameAddKeypoints(builder, keypoints)
        InputFrameAddHandSide(builder, self.handSide)
        InputFrameAddIsRelative(builder, self.isRelative)
        InputFrameAddCommand(builder, self.command)
        if self.coordinateFrame is not None:
            InputFrameAddCoordinateFrame(builder, coordinateFrame)
        inputFrame = InputFrameEnd(builder)
        return inputFrame
