# automatically generated by the FlatBuffers compiler, do not modify

# namespace: teleop

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class JointState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = JointState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsJointState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # JointState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # JointState
    def HandSide(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # JointState
    def JointPositionsRad(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # JointState
    def JointPositionsRadAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # JointState
    def JointPositionsRadLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # JointState
    def JointPositionsRadIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # JointState
    def Command(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # JointState
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def JointStateStart(builder): builder.StartObject(4)
def Start(builder):
    return JointStateStart(builder)
def JointStateAddHandSide(builder, handSide): builder.PrependUint8Slot(0, handSide, 0)
def AddHandSide(builder, handSide):
    return JointStateAddHandSide(builder, handSide)
def JointStateAddJointPositionsRad(builder, jointPositionsRad): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(jointPositionsRad), 0)
def AddJointPositionsRad(builder, jointPositionsRad):
    return JointStateAddJointPositionsRad(builder, jointPositionsRad)
def JointStateStartJointPositionsRadVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartJointPositionsRadVector(builder, numElems):
    return JointStateStartJointPositionsRadVector(builder, numElems)
def JointStateAddCommand(builder, command): builder.PrependUint8Slot(2, command, 0)
def AddCommand(builder, command):
    return JointStateAddCommand(builder, command)
def JointStateAddTimestamp(builder, timestamp): builder.PrependFloat64Slot(3, timestamp, 0.0)
def AddTimestamp(builder, timestamp):
    return JointStateAddTimestamp(builder, timestamp)
def JointStateEnd(builder): return builder.EndObject()
def End(builder):
    return JointStateEnd(builder)
try:
    from typing import List
except:
    pass

class JointStateT(object):

    # JointStateT
    def __init__(self):
        self.handSide = 0  # type: int
        self.jointPositionsRad = None  # type: List[float]
        self.command = 0  # type: int
        self.timestamp = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        jointState = JointState()
        jointState.Init(buf, pos)
        return cls.InitFromObj(jointState)

    @classmethod
    def InitFromObj(cls, jointState):
        x = JointStateT()
        x._UnPack(jointState)
        return x

    # JointStateT
    def _UnPack(self, jointState):
        if jointState is None:
            return
        self.handSide = jointState.HandSide()
        if not jointState.JointPositionsRadIsNone():
            if np is None:
                self.jointPositionsRad = []
                for i in range(jointState.JointPositionsRadLength()):
                    self.jointPositionsRad.append(jointState.JointPositionsRad(i))
            else:
                self.jointPositionsRad = jointState.JointPositionsRadAsNumpy()
        self.command = jointState.Command()
        self.timestamp = jointState.Timestamp()

    # JointStateT
    def Pack(self, builder):
        if self.jointPositionsRad is not None:
            if np is not None and type(self.jointPositionsRad) is np.ndarray:
                jointPositionsRad = builder.CreateNumpyVector(self.jointPositionsRad)
            else:
                JointStateStartJointPositionsRadVector(builder, len(self.jointPositionsRad))
                for i in reversed(range(len(self.jointPositionsRad))):
                    builder.PrependFloat32(self.jointPositionsRad[i])
                jointPositionsRad = builder.EndVector()
        JointStateStart(builder)
        JointStateAddHandSide(builder, self.handSide)
        if self.jointPositionsRad is not None:
            JointStateAddJointPositionsRad(builder, jointPositionsRad)
        JointStateAddCommand(builder, self.command)
        JointStateAddTimestamp(builder, self.timestamp)
        jointState = JointStateEnd(builder)
        return jointState
