# automatically generated by the FlatBuffers compiler, do not modify

# namespace: teleop

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class KeyboardInput(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KeyboardInput()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsKeyboardInput(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # KeyboardInput
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # KeyboardInput
    def KeyStates(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # KeyboardInput
    def KeyStatesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # KeyboardInput
    def KeyStatesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # KeyboardInput
    def KeyStatesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # KeyboardInput
    def HandSide(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # KeyboardInput
    def IsRelative(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # KeyboardInput
    def Command(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def KeyboardInputStart(builder): builder.StartObject(4)
def Start(builder):
    return KeyboardInputStart(builder)
def KeyboardInputAddKeyStates(builder, keyStates): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(keyStates), 0)
def AddKeyStates(builder, keyStates):
    return KeyboardInputAddKeyStates(builder, keyStates)
def KeyboardInputStartKeyStatesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartKeyStatesVector(builder, numElems):
    return KeyboardInputStartKeyStatesVector(builder, numElems)
def KeyboardInputAddHandSide(builder, handSide): builder.PrependUint8Slot(1, handSide, 0)
def AddHandSide(builder, handSide):
    return KeyboardInputAddHandSide(builder, handSide)
def KeyboardInputAddIsRelative(builder, isRelative): builder.PrependUint8Slot(2, isRelative, 0)
def AddIsRelative(builder, isRelative):
    return KeyboardInputAddIsRelative(builder, isRelative)
def KeyboardInputAddCommand(builder, command): builder.PrependUint8Slot(3, command, 0)
def AddCommand(builder, command):
    return KeyboardInputAddCommand(builder, command)
def KeyboardInputEnd(builder): return builder.EndObject()
def End(builder):
    return KeyboardInputEnd(builder)
try:
    from typing import List
except:
    pass

class KeyboardInputT(object):

    # KeyboardInputT
    def __init__(self):
        self.keyStates = None  # type: List[float]
        self.handSide = 0  # type: int
        self.isRelative = 0  # type: int
        self.command = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        keyboardInput = KeyboardInput()
        keyboardInput.Init(buf, pos)
        return cls.InitFromObj(keyboardInput)

    @classmethod
    def InitFromObj(cls, keyboardInput):
        x = KeyboardInputT()
        x._UnPack(keyboardInput)
        return x

    # KeyboardInputT
    def _UnPack(self, keyboardInput):
        if keyboardInput is None:
            return
        if not keyboardInput.KeyStatesIsNone():
            if np is None:
                self.keyStates = []
                for i in range(keyboardInput.KeyStatesLength()):
                    self.keyStates.append(keyboardInput.KeyStates(i))
            else:
                self.keyStates = keyboardInput.KeyStatesAsNumpy()
        self.handSide = keyboardInput.HandSide()
        self.isRelative = keyboardInput.IsRelative()
        self.command = keyboardInput.Command()

    # KeyboardInputT
    def Pack(self, builder):
        if self.keyStates is not None:
            if np is not None and type(self.keyStates) is np.ndarray:
                keyStates = builder.CreateNumpyVector(self.keyStates)
            else:
                KeyboardInputStartKeyStatesVector(builder, len(self.keyStates))
                for i in reversed(range(len(self.keyStates))):
                    builder.PrependFloat32(self.keyStates[i])
                keyStates = builder.EndVector()
        KeyboardInputStart(builder)
        if self.keyStates is not None:
            KeyboardInputAddKeyStates(builder, keyStates)
        KeyboardInputAddHandSide(builder, self.handSide)
        KeyboardInputAddIsRelative(builder, self.isRelative)
        KeyboardInputAddCommand(builder, self.command)
        keyboardInput = KeyboardInputEnd(builder)
        return keyboardInput
