# automatically generated by the FlatBuffers compiler, do not modify

# namespace: teleop

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VRInput(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VRInput()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVRInput(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VRInput
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VRInput
    def Keypoints(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # VRInput
    def KeypointsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # VRInput
    def KeypointsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VRInput
    def KeypointsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # VRInput
    def HandSide(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # VRInput
    def IsRelative(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # VRInput
    def Command(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # VRInput
    def HandOrientationQuat(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # VRInput
    def HandOrientationQuatAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # VRInput
    def HandOrientationQuatLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VRInput
    def HandOrientationQuatIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # VRInput
    def InputSource(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # VRInput
    def GripperTrigger(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def VRInputStart(builder): builder.StartObject(7)
def Start(builder):
    return VRInputStart(builder)
def VRInputAddKeypoints(builder, keypoints): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(keypoints), 0)
def AddKeypoints(builder, keypoints):
    return VRInputAddKeypoints(builder, keypoints)
def VRInputStartKeypointsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartKeypointsVector(builder, numElems):
    return VRInputStartKeypointsVector(builder, numElems)
def VRInputAddHandSide(builder, handSide): builder.PrependUint8Slot(1, handSide, 0)
def AddHandSide(builder, handSide):
    return VRInputAddHandSide(builder, handSide)
def VRInputAddIsRelative(builder, isRelative): builder.PrependUint8Slot(2, isRelative, 0)
def AddIsRelative(builder, isRelative):
    return VRInputAddIsRelative(builder, isRelative)
def VRInputAddCommand(builder, command): builder.PrependUint8Slot(3, command, 0)
def AddCommand(builder, command):
    return VRInputAddCommand(builder, command)
def VRInputAddHandOrientationQuat(builder, handOrientationQuat): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(handOrientationQuat), 0)
def AddHandOrientationQuat(builder, handOrientationQuat):
    return VRInputAddHandOrientationQuat(builder, handOrientationQuat)
def VRInputStartHandOrientationQuatVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartHandOrientationQuatVector(builder, numElems):
    return VRInputStartHandOrientationQuatVector(builder, numElems)
def VRInputAddInputSource(builder, inputSource): builder.PrependUint8Slot(5, inputSource, 0)
def AddInputSource(builder, inputSource):
    return VRInputAddInputSource(builder, inputSource)
def VRInputAddGripperTrigger(builder, gripperTrigger): builder.PrependFloat32Slot(6, gripperTrigger, 0.0)
def AddGripperTrigger(builder, gripperTrigger):
    return VRInputAddGripperTrigger(builder, gripperTrigger)
def VRInputEnd(builder): return builder.EndObject()
def End(builder):
    return VRInputEnd(builder)
try:
    from typing import List
except:
    pass

class VRInputT(object):

    # VRInputT
    def __init__(self):
        self.keypoints = None  # type: List[float]
        self.handSide = 0  # type: int
        self.isRelative = 0  # type: int
        self.command = 0  # type: int
        self.handOrientationQuat = None  # type: List[float]
        self.inputSource = 0  # type: int
        self.gripperTrigger = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        vrinput = VRInput()
        vrinput.Init(buf, pos)
        return cls.InitFromObj(vrinput)

    @classmethod
    def InitFromObj(cls, vrinput):
        x = VRInputT()
        x._UnPack(vrinput)
        return x

    # VRInputT
    def _UnPack(self, vrinput):
        if vrinput is None:
            return
        if not vrinput.KeypointsIsNone():
            if np is None:
                self.keypoints = []
                for i in range(vrinput.KeypointsLength()):
                    self.keypoints.append(vrinput.Keypoints(i))
            else:
                self.keypoints = vrinput.KeypointsAsNumpy()
        self.handSide = vrinput.HandSide()
        self.isRelative = vrinput.IsRelative()
        self.command = vrinput.Command()
        if not vrinput.HandOrientationQuatIsNone():
            if np is None:
                self.handOrientationQuat = []
                for i in range(vrinput.HandOrientationQuatLength()):
                    self.handOrientationQuat.append(vrinput.HandOrientationQuat(i))
            else:
                self.handOrientationQuat = vrinput.HandOrientationQuatAsNumpy()
        self.inputSource = vrinput.InputSource()
        self.gripperTrigger = vrinput.GripperTrigger()

    # VRInputT
    def Pack(self, builder):
        if self.keypoints is not None:
            if np is not None and type(self.keypoints) is np.ndarray:
                keypoints = builder.CreateNumpyVector(self.keypoints)
            else:
                VRInputStartKeypointsVector(builder, len(self.keypoints))
                for i in reversed(range(len(self.keypoints))):
                    builder.PrependFloat32(self.keypoints[i])
                keypoints = builder.EndVector()
        if self.handOrientationQuat is not None:
            if np is not None and type(self.handOrientationQuat) is np.ndarray:
                handOrientationQuat = builder.CreateNumpyVector(self.handOrientationQuat)
            else:
                VRInputStartHandOrientationQuatVector(builder, len(self.handOrientationQuat))
                for i in reversed(range(len(self.handOrientationQuat))):
                    builder.PrependFloat32(self.handOrientationQuat[i])
                handOrientationQuat = builder.EndVector()
        VRInputStart(builder)
        if self.keypoints is not None:
            VRInputAddKeypoints(builder, keypoints)
        VRInputAddHandSide(builder, self.handSide)
        VRInputAddIsRelative(builder, self.isRelative)
        VRInputAddCommand(builder, self.command)
        if self.handOrientationQuat is not None:
            VRInputAddHandOrientationQuat(builder, handOrientationQuat)
        VRInputAddInputSource(builder, self.inputSource)
        VRInputAddGripperTrigger(builder, self.gripperTrigger)
        vrinput = VRInputEnd(builder)
        return vrinput
